//! Architector — one per `(repo, milestone)`. Drives the milestone end-to-end.
//!
//! Architectors are tracked in the daemon's SQLite store and are surfaced in the
//! TUI. The architector itself is a long-running interactive claude session in a
//! tmux pane; this struct is the daemon-side handle, not the agent's runtime.

use serde::{Deserialize, Serialize};

/// Identity + state of one architector.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Architector {
    /// Stable identifier, generated by the daemon. ULID-shaped.
    pub id: String,
    /// `owner/name` of the GitHub repo this architector drives.
    pub repo: String,
    /// Logical milestone id within the active plan (e.g. `"M0"`).
    pub milestone_id: String,
    /// URL of the parent issue tracking the milestone.
    pub issue_url: String,
    /// Current lifecycle phase.
    pub state: ArchitectorState,
    /// ISO-8601 timestamp when the architector was registered.
    pub created_at: String,
}

/// Lifecycle phases for an architector. Tagged in JSON via `"state"`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "state", rename_all = "snake_case")]
pub enum ArchitectorState {
    /// Tmux pane being created, claude session warming up.
    Spawning,
    /// Architector is making progress.
    Active,
    /// Cannot proceed without user intervention.
    Stuck { reason: String },
    /// Milestone closed (shipped or dropped). Terminal.
    Closed { outcome: ArchitectorOutcome },
}

/// Terminal outcomes for an architector.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ArchitectorOutcome {
    Shipped,
    Dropped,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Architector {
        Architector {
            id: "01J0K2X9".to_owned(),
            repo: "a1f/claude-admin".to_owned(),
            milestone_id: "M0".to_owned(),
            issue_url: "https://github.com/a1f/claude-admin/issues/3".to_owned(),
            state: ArchitectorState::Active,
            created_at: "2026-05-04T06:30:00Z".to_owned(),
        }
    }

    #[test]
    fn architector_serde_roundtrip() {
        let a = sample();
        let json = serde_json::to_string(&a).unwrap();
        let parsed: Architector = serde_json::from_str(&json).unwrap();
        assert_eq!(a, parsed);
    }

    #[test]
    fn architector_state_stuck_carries_reason() {
        let a = Architector {
            state: ArchitectorState::Stuck {
                reason: "needs user input".to_owned(),
            },
            ..sample()
        };
        let json = serde_json::to_string(&a).unwrap();
        assert!(json.contains("\"reason\":\"needs user input\""));
        let parsed: Architector = serde_json::from_str(&json).unwrap();
        assert_eq!(a, parsed);
    }

    #[test]
    fn architector_state_closed_carries_outcome() {
        let a = Architector {
            state: ArchitectorState::Closed {
                outcome: ArchitectorOutcome::Shipped,
            },
            ..sample()
        };
        let json = serde_json::to_string(&a).unwrap();
        assert!(json.contains("\"outcome\":\"shipped\""));
        let parsed: Architector = serde_json::from_str(&json).unwrap();
        assert_eq!(a, parsed);
    }
}
